services:
  app:
    build:
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: >
      sh -c "
      sleep 2 &&
      goose -dir db/migrations postgres $DATABASE_URL up &&
      /usr/src/jobportal/app" 

  postgres:
    container_name: postgres
    image: postgres:17
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - '5433:5432'
    restart:
      unless-stopped

volumes:
  postgres-data: