services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/jobportal
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    container_name: postgres
    image: postgres:17
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5433:5432'
    restart:
      unless-stopped

volumes:
  postgres-data: