// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int64
	FirstName pgtype.Text
	LastName  pgtype.Text
	Email     string
	Password  pgtype.Text
}
